global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api_gateway"
    static_configs:
      - targets: ["api-gateway-service:9090"]

  - job_name: "auth_service"
    static_configs:
      - targets: ["auth-service:9090"]

  - job_name: "blog_service"
    static_configs:
      - targets: ["blog-service:9090"]
