apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: your_docker_registry/notification-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:password@<rabbitmq-host>:5672/"
            - name: DB_URL
              value: "<database-connection-url>"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
