apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000 # Choose a port within the range 30000-32767
  selector:
    app: api-gateway
