apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: teklumt/api:auth_service0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: MYSQL_URL
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: RABBITMQ_URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: JWT_SECRET
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
