apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: teklumt/api:userservice0.0
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_URL
              value: "amqp://admin:password@rabbitmq:5672/"
            - name: DB_URL
              value: "root:root@tcp(mysql:3306)/blog_db?charset=utf8mb4&parseTime=True&loc=Local"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
